[GLOBAL]
pants_version = "2.10.0rc0"
backend_packages = [
  "pants.backend.codegen.protobuf.python",
  "pants.backend.codegen.thrift.apache.python",
  "pants.backend.python",
]

use_deprecated_python_macros = false

[source]
# These are the default, but we list them explicitly for instruction.
# See https://www.pantsbuild.org/docs/source-roots
root_patterns = [
    "/src/python",
    "/src/protobuf",
    "/src/thrift",
]

[anonymous-telemetry]
enabled = true
repo_id = "205E301D-44A4-42FF-8495-C9D41871A431"

[python]
interpreter_constraints = ["CPython>=3.8,<3.11"]
enable_resolves = true

[python-protobuf]
runtime_dependencies = ["3rdparty/python#protobuf"]

[python-thrift]
runtime_dependencies = ["3rdparty/python#thrift"]
